name: CMS Deploy to Fly.io ğŸª

on:
  push:
    branches:
      - main
      - mastodon-mountainash

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-fly-group

    steps:
      - name: Checkout on branch ${{ github.ref_name }} ğŸ“¥
        uses: actions/checkout@v4

      - name: Install Fly CLI ğŸ“¦
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io ğŸª
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy ./ --yes