name: CMS Deploy to Fly.io ğŸª

on:
  push:
    branches:
      - mastodon-mountainash

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch ğŸ“¥
        uses: actions/checkout@v4

      - name: Install Fly CLI ğŸ§±
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io ğŸª
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy ./ --ha=false --yes --now